Chore/dashboard updated
oscarlagatta/home-improvement-hub pull request #13
Opened 2024-11-18 16:11 UTC by alamuk

Updated the dashboard libs

2024-11-18 23:27 UTC, oscarlagatta requested changes
Please address the comments and call for another review, thank you for your hard work.

2024-11-18 23:27 UTC, oscarlagatta commented on apps/home-improvement-hub/src/app/app.tsx
> +      <h1>Hello App</h1>
Remove the Hello App H1, and return a div with a message welcome to app

2024-11-18 23:27 UTC, oscarlagatta commented on libs/dashboard/dashboard-ui/src/lib/main-nav.tsx
create a folder for pages and create a folder for components

2024-11-18 23:27 UTC, oscarlagatta commented on libs/dashboard/dashboard-utility/project.json
> +  "tags": [],
add the tags definitions, eg. scope:dashboard,type:feature

2024-11-18 23:27 UTC, oscarlagatta commented on libs/dashboard/features/feature-recent-sales/project.json
> +  "tags": [],
add the tags for this library as for the others

2024-11-18 23:29 UTC, Moshe-Victor approved these changes

2024-11-19 10:50 UTC, oscarlagatta approved these changes

2024-11-19 10:50 UTC, merged